---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_pass
    repo: elhindi/flask-pg-app
    tags:
      - 'v0.1'
      - "${DRONE_BUILD}"
      - latest

---
kind: pipeline
type: docker
name: infra

platform:
  os: linux
  arch: amd64

steps:
- name: terraform
  terraform:
    image: jmccann/drone-terraform:1
    plan: false
    #sensitive: true
    root_dir: infra/modules/terraform-google-kubernetes-engine/examples/deploy_service
    remote:
    backend: gcs
      config:
        bucket: terraform
        key: "${DRONE_BRANCH}"/tf-states/my-project
        region: eu-west-2

---
# kind: pipeline
# name: deploy

# gke:
#   image: nytimes/drone-gke
#   kubectl_version: "1.14"
#   zone: eu-west2-a
#   cluster: my-gke-cluster
#   namespace: ${DRONE_BRANCH}
#   environment:
#     - USER=root
#   expand_env_vars: true
#   vars:
#     image: docker.io/elhindi/flask-pg-app:v0.1 #${DRONE_COMMIT} #${BUILD_NUMBER}
#     app: flask
#     env: ${DRONE_BRANCH}
#     user: $${USER}
#   secrets:
#     - source: GOOGLE_CREDENTIALS
#       target: token
#     - source: APP_API_KEY
#       target: secret_api_token
#     - source: P12_CERT
#       target: secret_base64_p12_cert

  trigger:
    branch:
    - develop
    event:
    - push
    - pull_request

  depends_on:
    - infra
    - build
